### PR TITLE
fix: add changes made to other functional test compose files (release…

### PR DESCRIPTION
**Pull request by Rob-Doherty**
### JIRA link

https://tools.hmcts.net/jira/browse/ROC-8369

### Change description

Fix functional smoke tests in similar way to the release pipeline tests (https://github.com/hmcts/cmc-legal-rep-frontend/pull/832)

### Work checklist

- [ ] Unit tests added where applicable
- [ ] Route tests added for new pages
- [ ] New pages included in a11y tests
- [ ] Task list and task completeness checks updated
- [ ] Check and send page updated
- [ ] Routes, page content and page flows of new features are toggled
- [ ] UI changes look good on mobile
- [ ] Required Google Analytics events are being sent

### Developer self-QA run statement

- [ ] I have clicked through the running application to see if all changes I made actually work.

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by ThirumuruganD — CHANGES_REQUESTED** [review]
can we also update web driver version
remote-webdriver:
      image: selenium/standalone-chrome:3.8.1

**Comment by Rob-Doherty** [comment]
As per our chat @ThirumuruganD, I've made that changes so that all the functional tests are running a consistent version of `selenium/standalone-chrome`.
can you please re-review, thanks

**Review by ThirumuruganD — APPROVED** [review]
looks good

**Review by sunilkumar-cts — APPROVED** [review]
Ready to be merged

**Pull request merged**
