### PR TITLE
TA-382: Add retries to @smoke-test tagged e2e test

### PR DESCRIPTION
**Pull request by Rob-Doherty**
### JIRA link

https://tools.hmcts.net/jira/browse/TA-382

### Change description

Allow @smoke-test tagged e2e test to retry up to 2 times, for benefit of the nightly crossbrowser pipeline where the risk of network or environmental flakiness causing false negatives (i.e. breaking the build) is higher.

### Work checklist

- [ ] Unit tests added where applicable
- [ ] Route tests added for new pages
- [ ] New pages included in a11y tests
- [ ] Task list and task completeness checks updated
- [ ] Check and send page updated
- [ ] Routes, page content and page flows of new features are toggled
- [ ] UI changes look good on mobile
- [ ] Required Google Analytics events are being sent

### Developer self-QA run statement

- [ ] I have clicked through the running application to see if all changes I made actually work.

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

Nightly pipeline passes:

image

### CODE REVIEW

**Comment by Rob-Doherty** [comment]
Nightly pipeline passes

image

**Review by pradhap87 — APPROVED** [review]
Hi Rob,
IDAM team is suggesting to avoid re-try in the test cases as it is putting more load on the IDAM (Multiple request due to re-try).

@yogendraU FYI ... your thought on this ?

**Review by paulnisbett-hmcts — APPROVED** [review]
approved - retry added

**Comment by yogendraU** [comment]
> Hi Rob,
> IDAM team is suggesting to avoid re-try in the test cases as it is putting more load on the IDAM (Multiple request due to re-try).
> 
> @yogendraU FYI ... your thought on this ?

Yes Prathap. you rightly pointed. However since, this is legal Rep application, we can add retries. however, for claim store or Citizen front end, we wont be adding any retries.

**Comment by yogendraU** [comment]
Yes Prathap. you rightly pointed. However since, this is legal Rep application, we can add retries. however, for claim store or Citizen front end, we wont be adding any retries

**Review by yogendraU — APPROVED** [review]

**Pull request merged**
